Repository containers/podlet, pull requests merged in 2024-05, with the labels that each got.

#75 Podman v5.0.0
  Cargo.toml
  clippy.toml
  src/cli.rs
  src/cli/compose.rs
  src/cli/container.rs
  src/cli/container/compose.rs
  src/cli/container/podman.rs
  src/cli/container/quadlet.rs
  src/cli/generate.rs
  src/cli/global_args.rs
  src/cli/image.rs
  src/cli/install.rs
  src/cli/kube.rs
  src/cli/network.rs
  src/cli/pod.rs
  src/cli/unit.rs
  src/cli/volume.rs
  src/quadlet.rs
  src/quadlet/container.rs
  src/quadlet/container/mount.rs
  src/quadlet/kube.rs
  src/quadlet/pod.rs
  src/serde/args.rs
  src/serde/mount_options/ser.rs
  src/serde/quadlet.rs
Labels: enhancement

#78 docs(changelog): fix v0.3.0 release date
  CHANGELOG.md
Labels: documentation

#80 docs: add homebrew to the installation section
  README.md
Labels: documentation

#83 ci(release-container): add `--all` to `buildah manifest push`
  .github/workflows/release-container.yml
Labels: ci
